In [48]:
import pandas as pd
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

data_path = '/workspaces/Final-Year-Project/Cleaned Data/TrainTestData.csv'
df = pd.read_csv(data_path)

X = df.drop('Diabetes Status', axis=1)
y = df['Diabetes Status']

scaler = StandardScaler()
X = scaler.fit_transform(X)

dt = DecisionTreeClassifier(random_state=42, class_weight='balanced')

param_grid = {
    'max_depth': [None, 5, 10, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5],
    'max_features': ['sqrt', 'log2', None],
    'class_weight': ['balanced']  # Add class weight as an option
}

kf = KFold(n_splits=5, shuffle=True, random_state=42)
grid_search = GridSearchCV(dt, param_grid, scoring='accuracy', cv=kf, n_jobs=-1, verbose=1)

grid_search.fit(X, y)

best_dt = grid_search.best_estimator_

y_pred = best_dt.predict(X)

print("Best Parameters for Decision Tree:", grid_search.best_params_)
print("Mean Accuracy with Best Parameters:", grid_search.best_score_)


print("Decision Tree Classification Report:")
print(classification_report(y, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))


Fitting 5 folds for each of 135 candidates, totalling 675 fits
Best Parameters for Decision Tree: {'class_weight': 'balanced', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Mean Accuracy with Best Parameters: 0.5375324906533737
Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.68      0.67       679
           1       0.51      0.45      0.48       688
           2       0.64      0.70      0.67       685

    accuracy                           0.61      2052
   macro avg       0.61      0.61      0.61      2052
weighted avg       0.60      0.61      0.61      2052

Confusion Matrix:
[[464 147  68]
 [173 309 206]
 [ 60 146 479]]


In [36]:
df['Diabetes Status'].value_counts()

Diabetes Status
2    695
1    695
0    689
Name: count, dtype: int64

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Load the dataset
data_path = '/workspaces/Final-Year-Project/Cleaned Data/TrainTestData.csv'
df = pd.read_csv(data_path)

# Define features and target directly from the dataset
X = df.drop('Diabetes Status', axis=1)
y = df['Diabetes Status']

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Initialize the Random Forest model with class weights
rf = RandomForestClassifier(random_state=42, class_weight='balanced')

# Set up the hyperparameter grid for tuning
param_grid = {
    'n_estimators': [100, 200, 300],        # Number of trees in the forest
    'max_depth': [None, 5, 10, 15, 20],      # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],         # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 5],           # Minimum number of samples required to be at a leaf node
    'max_features': ['sqrt', 'log2', None], # The number of features to consider when looking for the best split
    'bootstrap': [True, False]               # Whether bootstrap samples are used when building trees
}

# Use GridSearchCV with KFold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)
grid_search = GridSearchCV(rf, param_grid, scoring='accuracy', cv=kf, n_jobs=-1, verbose=1)

# Fit GridSearchCV on the data
grid_search.fit(X, y)

# Get the best model
best_rf = grid_search.best_estimator_

# Evaluate the model with the best parameters on the entire dataset (since we're using cross-validation)
y_pred_rf = best_rf.predict(X)

# Print the best hyperparameters and the mean accuracy from cross-validation
print("Best Parameters for Random Forest:", grid_search.best_params_)
print("Mean Accuracy with Best Parameters:", grid_search.best_score_)

# Classification report and confusion matrix
print("\nRandom Forest Classification Report:")
print(classification_report(y, y_pred_rf))
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred_rf))


Fitting 5 folds for each of 810 candidates, totalling 4050 fits
